<a href="https://colab.research.google.com/github/dtuleva/DL_23_Lectures_and_Quests/blob/main/bonus_lecture_PyTorch_and__JAX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np

import torch

# PyTorch and JAX
### bonus lecture

In [2]:
torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
torch.Tensor(2, 5) # 2, 5 is shape; makes a tensor that is not initialised; values are whatever happens to be in memory

tensor([[3.0221e+32, 8.9068e-15, 2.0704e-19, 2.7565e+12, 6.9785e+22],
        [7.5556e+31, 1.5768e-19, 4.2324e+21, 6.8888e+22, 4.4591e+30]])

In [4]:
torch.zeros(2, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
torch.ones(2, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [26]:
a = torch.rand((2000, 6)) # torch.random for other distributions
b = torch.rand((2000, 6))
w = torch.rand((6, 1)) # broadcasting - rank 1 tensor does not transpose properly (same as numpy)

In [27]:
a == b

tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        ...,
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]])

In [28]:
torch.all(a == b)

tensor(False)

In [30]:
torch.all((a + b) == torch.add(a, b))

tensor(True)

In [33]:
a @ b.T

tensor([[2.0515, 1.1019, 2.0896,  ..., 1.8781, 1.5323, 1.3784],
        [1.1844, 0.5961, 1.2851,  ..., 1.3839, 1.3026, 1.1775],
        [1.7176, 0.5805, 1.7451,  ..., 1.9654, 1.6873, 1.8770],
        ...,
        [1.6369, 0.8913, 1.8754,  ..., 1.8238, 2.0730, 1.6184],
        [1.4304, 0.7652, 1.6221,  ..., 1.4995, 1.3009, 1.2881],
        [0.6894, 0.5261, 1.0284,  ..., 0.6456, 1.2559, 0.7867]])

In [35]:
torch.matmul(b, a.T)

tensor([[2.0515, 1.1844, 1.7176,  ..., 1.6369, 1.4304, 0.6894],
        [1.1019, 0.5961, 0.5805,  ..., 0.8913, 0.7652, 0.5261],
        [2.0896, 1.2851, 1.7451,  ..., 1.8754, 1.6221, 1.0284],
        ...,
        [1.8781, 1.3839, 1.9654,  ..., 1.8238, 1.4995, 0.6456],
        [1.5323, 1.3026, 1.6873,  ..., 2.0730, 1.3009, 1.2559],
        [1.3784, 1.1775, 1.8770,  ..., 1.6184, 1.2881, 0.7867]])

In [38]:
(a @ w).shape

torch.Size([2000, 1])

In [42]:
z = a @ w + b

In [44]:
z.min()

tensor(0.2851)

In [41]:
torch.relu(z)

tensor([[2.2321, 2.7146, 1.8869, 2.1619, 2.6045, 2.0364],
        [1.6818, 1.8088, 1.8714, 1.9938, 2.3606, 1.6485],
        [2.3686, 2.6794, 2.3008, 2.6176, 2.7673, 2.2022],
        ...,
        [2.9925, 2.6922, 2.3296, 2.2344, 2.7687, 2.8540],
        [1.6953, 1.8640, 2.1309, 2.0331, 1.4892, 1.9086],
        [1.3251, 1.5032, 0.9667, 1.3226, 0.8722, 1.3571]])

In [48]:
x_np = np.linspace(-5, 5, 5000)
y_np = np.sin(x_np)

In [51]:
x_torch = torch.tensor(x_np)
type(x_torch)

torch.Tensor

In [53]:
torch.sin(x_np) # cannot feed np array directly to torch function

TypeError: ignored

In [55]:
y_torch = torch.sin(x_torch)
# or
x_torch.sin()

tensor([ 0.9589,  0.9595,  0.9601,  ..., -0.9601, -0.9595, -0.9589],
       dtype=torch.float64)

In [57]:
# can be chained for unary operations
torch.all(x_torch.sin().cos()) == torch.all(torch.cos(torch.sin(x_torch)))

tensor(True)

In [60]:
x_torch[:4]

tensor([-5.0000, -4.9980, -4.9960, -4.9940], dtype=torch.float64)

In [61]:
a

tensor([[0.3813, 0.7953, 0.6023, 0.3146, 0.9928, 0.1448],
        [0.0260, 0.3393, 0.2938, 0.4114, 0.4557, 0.8604],
        [0.5277, 0.7079, 0.0279, 0.7140, 0.2600, 0.9134],
        ...,
        [0.0020, 0.5616, 0.9106, 0.5456, 0.5573, 0.9432],
        [0.7844, 0.2344, 0.2062, 0.8122, 0.5131, 0.0908],
        [0.1464, 0.1212, 0.7608, 0.6751, 0.1295, 0.0342]])

In [63]:
a[:, 1]

tensor([0.7953, 0.3393, 0.7079,  ..., 0.5616, 0.2344, 0.1212])

Gradients

In [64]:
y_torch

tensor([ 0.9589,  0.9595,  0.9601,  ..., -0.9601, -0.9595, -0.9589],
       dtype=torch.float64)

In [65]:
y_torch.requires_grad

False

In [66]:
type(y_torch.grad)

NoneType

In [68]:
x_torch = torch.tensor(x_np, requires_grad = True) # state that gradients are needed by initialisation / reinitialisation of variable
# x_torch = torch.tensor(x_torch, requires_grad = True)


In [69]:
y_torch = torch.sin(x_torch)

In [71]:
y_torch.backward()

RuntimeError: ignored

In [72]:
y_torch.grad

<ipython-input-72-8de13210a3da>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  y_torch.grad


In [73]:
x_torch.grad

In [75]:
a = torch.tensor([2, 3, 5], dtype = float, requires_grad = True)
b = torch.tensor([8.0, 15, -2])


In [76]:
y = (2 * a ** 2 + 3 * b)** 3

In [77]:
y.backward()

RuntimeError: ignored