<a href="https://colab.research.google.com/github/dtuleva/DL_23_Lectures_and_Quests/blob/main/paper_1_code_Language_agnostic_BERT_Sentence_Embedding_kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q tensorflow-text

In [ ]:
import tensorflow_hub as hub
import tensorflow as tf
import tensorflow_text as text  # Needed for loading universal-sentence-encoder-cmlm/multilingual-preprocess
import numpy as np

# Language-agnostic BERT Sentence Embedding

We publicly release our best
multilingual sentence embedding model for
109+ languages at https://tfhub.dev/
google/LaBSE. (tf hub is now kaggle models)

In [ ]:
def normalization(embeds):
  norms = np.linalg.norm(embeds, 2, axis=1, keepdims=True)
  return embeds/norms

english_sentences = tf.constant(["dog", "Puppies are nice.", "I enjoy taking long walks along the beach with my dog."])
italian_sentences = tf.constant(["cane", "I cuccioli sono carini.", "Mi piace fare lunghe passeggiate lungo la spiaggia con il mio cane."])
japanese_sentences = tf.constant(["犬", "子犬はいいです", "私は犬と一緒にビーチを散歩するのが好きです"])
bulgarian_sentences = tf.constant(["куче", "Кученцата са сладки.", "Аз обичам дълги разходки по плажа с моето куче."])
bulgarian_me_sentences = tf.constant(["котка", "Не обичам кучета", "Който измисля изречения с кучета, а не с котки не е човек."])

preprocessor = hub.KerasLayer(
    "https://kaggle.com/models/google/universal-sentence-encoder/frameworks/TensorFlow2/variations/cmlm-multilingual-preprocess/versions/2")
encoder = hub.KerasLayer("https://www.kaggle.com/models/google/labse/frameworks/TensorFlow2/variations/labse/versions/2")

english_embeds = encoder(preprocessor(english_sentences))["default"]
japanese_embeds = encoder(preprocessor(japanese_sentences))["default"]
italian_embeds = encoder(preprocessor(italian_sentences))["default"]

# For semantic similarity tasks, apply l2 normalization to embeddings
english_embeds = normalization(english_embeds)
japanese_embeds = normalization(japanese_embeds)
italian_embeds = normalization(italian_embeds)

print (np.matmul(english_embeds, np.transpose(italian_embeds)))

# English-Japanese similarity
print (np.matmul(english_embeds, np.transpose(japanese_embeds)))

# Italian-Japanese similarity
print (np.matmul(italian_embeds, np.transpose(japanese_embeds)))


[[0.63192916 0.3061978  0.44297475]
 [0.11652706 0.8596665  0.3594056 ]
 [0.14804004 0.32447967 0.95426506]]
[[0.9356719  0.5403067  0.46792293]
 [0.31804198 0.76222503 0.360859  ]
 [0.36750716 0.4279154  0.8171454 ]]
[[0.5343722  0.25018638 0.19974728]
 [0.301408   0.7133319  0.40647534]
 [0.3850307  0.4776789  0.86742985]]
